### ISSUE TITLE
L2 constructs for Cluster, Project, ServerlessInstance, NetworkPeering and PrivateEndpoint etc.

### ISSUE THREAD

**Issue by pahud** [mongodb/awscdk-resources-mongodbatlas#112]
**Is your feature request related to a problem? Please describe.**
At this moment, we are still missing a lot of frequent L2 constructs including `Cluster`, `ServerlessInstance` and `Project`.

The general idea of the L2 construct is:

1. It allows developer to create MongoDB Atlas resources with sensible defaults with very minimal required properties only for a single CfnResource.
2. It allows to create a "reference" object from existing resource with  the `from` methods such as `Xxx.fromAttributes()` or `Xxx.fromXxxId()`.
3. It offers opinionated construct methods such as `Xxx.addCluster()` or `Xxx.addComponent()`.
4. As all L2s are extended from CfnResource, they inherit some build-in capabilities as static methods defined in the [CfnResource class](https://github.com/aws/aws-cdk/blob/112b8619d60dd9082be92cb811cc5c7f36f05fe1/packages/aws-cdk-lib/core/lib/cfn-resource.ts#L35).

Let's take CfnProject for example, the L2 `Project` should look like this:

```ts
import { Resource, ResourceProps } from 'aws-cdk-lib';
import { CfnProject } from 'awscdk-resources-mongodbatlas';
import { Construct } from 'constructs';
import { ProjectOptions } from './types';

export interface IProject {
  readonly clusterCount?: number;
  readonly projectId: string;
  readonly projectName: string;
  readonly created?: string;
  readonly projectOwnerId: string;
}

export interface ProjectAttributes {
  readonly projectId: string;
  readonly projectName: string;
  readonly projectOwnerId: string;
}

export interface ProjectProps extends ResourceProps, ProjectOptions {
  readonly profile: string;
}

export class Project extends Resource implements IProject {
  public static fromProjectAttributes(scope: Construct, id: string, attrs: ProjectAttributes): IProject {
    class Import extends Resource {
      public projectId = attrs.projectId;
      public projectName = attrs.projectName;
      public projectOwnerId = attrs.projectOwnerId;
    };
    return new Import(scope, id);
  }
  readonly clusterCount?: number;
  readonly projectId: string;
  readonly created?: string;
  readonly projectOwnerId: string;
  readonly projectName: string;

  constructor(scope: Construct, id: string, props: ProjectProps) {
    super(scope, id);

    this.projectName = props.name ?? `project-${id}`;
    const resource = new CfnProject(this, 'Resource', {
      ...props,
      profile: props.profile,
      orgId: props.orgId,
      name: this.projectName,
    });
    this.clusterCount = resource.attrClusterCount;
    this.projectId = resource.attrId;
    this.created = resource.attrCreated;
    this.projectOwnerId = resource.attrProjectOwnerId;
  }
}
```

And customer can create a single Project by

```ts
const newProject = new Project(scope, id, {
  profile: 'default',
});
```
Or simply import an existing one as a reference object like

```ts
const existingProject = Project.fromProjectAttributes(scope, id, {
   projectId,
   projectName: 'my-manual-created-project',
   projectOwnerId: 'the-owner-id',
});
```

And when we create a single cluster in an `existing project` we should be allowed to 

```ts
new Cluster(scope, id, {
    project: existingProject,
    ...
```

Similarly, if we need to build a VPC Peering with L2 construct, the DX should be like

```ts
// define my existing VPC
const vpc = ec2.Vpc.fromLookup(scope, 'Vpc', { isDefault: true});

// create a new VPC Peering for an existing project with an existing VPC from AWS.
new NetworkPeering(scope, id, {
    project: existingProject,
    vpc: existingVpc,
};
```

which implicitly assume `routeTableCidrBlock` as `props.vpc.vpcCidrBlock` and `awsAccountId` the deploying AWS account ID by default unless explicitly defined. 

This makes the L2 experience consistent with AWS CDK if customers are running both AWS services such as Amazon API Gateway, AWS Lambda, Amazon ECS, Amazon EKS with MongoDB Atlas resources altogether in a single CDK application.

**Describe the solution you'd like**

As mentioned above, we should provide some most frequently used L2 constructs such as `Cluster`, `Project`, `ServerlessInstance`, etc.

**Describe alternatives you've considered**

**Additional context**

I will start working on PRs for some L2s mentioned above. The goal is to build seamless and consistent developer experience to create MongoDB Atlas resources in AWS.

**Comment by Adelmar92** [comment]
Hello @pahud this is a grate suggestion, we added this to the backlog hoping to target them soon!

**Comment by pahud** [comment]
Hi @Adelmar92 

I will create some samples in my repo this week and share with you.
