### ISSUE TITLE
CDK deployment is requiring a non empty ip access list

### ISSUE THREAD

**Issue by deanmcpherson** [mongodb/awscdk-resources-mongodbatlas#138]
**Describe the bug**

CDK deployment is requiring a non empty ip access list

**To Reproduce**

Deploy a basic mongo instance and set either:

```
ipAccessListProps: {
          accessList: [
          
          ],
        },
```

or don't set `ipAccessListProps` at all.

**Expected behavior**

The cluster stands up with no IP access provioned. E.g. we're using a private endpoint and don't want/need any IP access to the cluster.

We also tried expiring ip access as a short term solution, but it prevents stacks from deploying after the IP address has expired (we get errors like `"You have no entry in the accesslist. You should use CREATE instead of UPDATE"`

**Screenshots**
<img width="295" alt="Screen Shot 2023-09-29 at 11 55 40 am" src="https://github.com/mongodb/awscdk-resources-mongodbatlas/assets/2773950/4fa8cbd6-db3a-4a1c-9857-2fd8bec10c85">

**Comment by AgustinBettati** [comment]
Hello @deanmcpherson.

Thank you for bringing this up. I was able to reproduce the issue making use of the L3 AtlasBasic resource. We will look into what alternatives we have for supporting this use case and get back to you.

**Comment by deanmcpherson** [comment]
Appreciate it @AgustinBettati

**Comment by Adelmar92** [comment]
hello! @deanmcpherson after investigation we came to the conclusion that the L3 atlas basic is part of the MongoDB Basic pattern, and it requires a IPAccessList as part of the security access, so we made this property as mandatory.
