### ISSUE TITLE
l3 resource atlas-basic-private-endpoint should allow changing securitygroup

### ISSUE THREAD

**Issue by sanyer** [mongodb/awscdk-resources-mongodbatlas#158]
**Is your feature request related to a problem? Please describe.**
Currently, l3 resource `atlas-basic-private-endpoint` doens't allow changing securitygroup used for `ec2.CfnVPCEndpoint` resource.

**Describe the solution you'd like**
Allow changing securitygroup for the encapsulated resource `ec2.CfnVPCEndpoint`.

**Describe alternatives you've considered**
Using l1 resources and configuring it all manually.

**Additional context**
Using l1 resources gives more control but takes a ton of convenience away.

**Comment by Zuhairahmed** [comment]
Thanks @sanyer . This item is on our roadmap, but likely several quarters away. Will keep this ticket open over the interim.

**Comment by Zuhairahmed** [comment]
hi this item has been added to our backlog, but is unlikely we are able to tackle anytime soon. resolving this issue as will not complete in the near-term. including link for internal tracking purposes https://jira.mongodb.org/browse/CLOUDP-215120. thank you for your understanding.
