### ISSUE TITLE
CfnNetworkContainer requires providerName parameter despite it not being a valid prop

### ISSUE THREAD

**Issue by Defrosted** [mongodb/awscdk-resources-mongodbatlas#163]
**Describe the bug**
When attempting to use the CfnNetworkContainer construct to get/create a network container for a cluster, the deployment for it fails with `Resource handler returned message: "Unable to complete request: error Containers.ListAll err:providerName is required and must be specified"`. However, `providerName` is not a prop you can give to the construct.

**To Reproduce**
Try to deploy a CfnNetworkContainer construct using CDK to a MongoDB Atlas cluster.

Example:
```TypeScript
new CfnNetworkContainer(scope, 'mongodb-atlas-vpc', {
  projectId: mongoDbCluster.mProject.attrId,
  regionName: 'EU_NORTH_1',
  atlasCidrBlock: '192.168.248.0/21',
  profile: props.stage,
  provisioned: true,
});
```

**Expected behavior**
Expected to be able to create/get a network container so I can initiate VPC peering via CDK. Expected to be able to pass `providerName` as a prop since it's apparently required for the Atlas API call.

**Please complete the following information:**
 - CFN resource version: 2.0.0
 - AWS region where you are running the CFN stack: eu-north-1
 - CDK constructor type and version:
   - "awscdk-resources-mongodbatlas": "^3.0.0",
 - Copy of the output of `cdk synth`: Synth doesn't produce any errors

**Comment by Defrosted** [comment]
Seems like the `CfnNetworkContainer` construct works if I create it before creating a cluster in the project. However, this prevents me from using the `AtlasBasic` construct anymore, as the project needs to be created before the network container. Apparently, there's no way to get details from an existing network container using the `CfnNetworkContainer` construct after cluster provisioning; this would be a nice feature to have.

Initiating the VPC peering with the `CfnNetworkPeering` construct seems to be working nicely after doing this hurdle. It still needs to be accepted manually in AWS VPC, but that was to be expected.

**Comment by maastha** [comment]
Hi @Defrosted 
Thank you for bringing up this issue. We have merged the fix for this resource here https://github.com/mongodb/mongodbatlas-cloudformation-resources/pull/858 

This will be available in our next release, we will share the release date soon.

**Comment by maastha** [comment]
Hi @Defrosted 
We have released a new Cloudformation version of this resource with the fix for this issue. 
Please ensure to activate version 2.0.1 of MongoDB::Atlas::NetworkContainer in your AWS account before trying again.

Please let us know if you have any questions.

**Comment by maastha** [comment]
Hi @Defrosted
We have released a new Cloudformation extension version of this resource with the fix for this issue.
Please ensure to activate version 2.0.1 of MongoDB::Atlas::NetworkContainer in your AWS account before trying again.

Please let us know if you have any questions and re-open if required
