### ISSUE TITLE
CfnServerlessInstance does not return connection strings like CfnCluster does

### ISSUE THREAD

**Issue by Defrosted** [mongodb/awscdk-resources-mongodbatlas#164]
**Describe the bug**
Using `CfnServerlessInstance` does not return connection strings for the database. On the other hand, `CfnCluster` does. Therefore, there is no way of getting connection strings for Serverless instances via CDK. This is pretty crucial for streamlining integrating Atlas constructs with other infrastructure.

Looking at the definitions in CloudFormation as well as the Go code in the repo, it seems that the `MongoDB::Atlas::ServerlessInstance` CFN resource would have the same `ConnectionStrings` attribute defined that should be populated. It's just not mapped to the CDK construct in the current?

**To Reproduce**
Create a `CfnServerlessInstance`. The construct does not contain connection strings. There does seem to be a `connectionStrings` under the `props` attribute of the construct that even has a `ServerlessInstanceConnectionStrings` type defined, but those do not get populated upon deployment. This is extremely confusing, since for `CfnCluster` there is a direct `connectionStrings` attribute available that gets populated upon deployment. Now it seems I have to create a CustomResource that fetches the connection strings from Atlas API just for the serverless instance.

**Expected behavior**
Expected to get connection strings after creating a Serverless Instance in Atlas.

**Please complete the following information:**
 - CFN resource version: 2.0.0
 - AWS region where you are running the CFN stack: eu-north-1
 - CDK constructor type and version: 3.0.0
 - Copy of the output of `cdk synth`: No errors by synth

**Comment by Defrosted** [comment]
Managed to get a working workaround: `mongoServerless.getAtt('ConnectionStrings.StandardSrv').toString()`, where `mongoServerless` is an instance of `CfnServerlessInstance`. This directly gets the value from the CFN resource since it's not mapped to the CDK construct.

**Comment by maastha** [comment]
Hi @Defrosted 
Based on the workaround you shared, I am not sure I understand the issue. You are right that CfnServerlessInstance does have ConnectionsStrings property which contains `StandardSrv` and this structure is closely mapped to our [API](https://www.mongodb.com/docs/atlas/reference/api-resources-spec/v2/#tag/Serverless-Instances/operation/getServerlessInstance) for this resource which might not always have the same response attributes/structure as the Cluster APIs.

You may find more details and useful links in the resource [Readme](https://github.com/mongodb/awscdk-resources-mongodbatlas/tree/main/src/l1-resources/serverless-instance)

Closing this issue for now, please feel free to re-open with additional details (CDK code, etc) if needed.

**Comment by Defrosted** [comment]
The issue is, that `CfnServerlessInstance` should have a `connectionStrings` attribute under it in the CDK construct, but it does not. They are not mapped to the CDK construct. That's why the workaround is to get the values directly from CFN using the `getAtt` function. This is not concise since the `CfnCluster` has said connection strings under the construct.
