### ISSUE TITLE
Can't create FederatedDatabaseInstance

### ISSUE THREAD

**Issue by flochaz** [mongodb/awscdk-resources-mongodbatlas#174]
**Describe the bug**
Getting 
```
 ❌  dev-Backend failed: Error: The stack named dev-Backend failed to deploy: UPDATE_ROLLBACK_COMPLETE: Properties validation failed for resource DbFederatedDb5570C1CE with message:
#: required key [CloudProviderConfig/RoleId] not found
#: required key [CloudProviderConfig/TestS3Bucket] not found
#: required key [DataProcessRegion/Region] not found
```

Tried to not specifying it at all since it is listed as optional : 

```
  "DbFederatedDb5570C1CE": {
   "Type": "MongoDB::Atlas::FederatedDatabaseInstance",
   "Properties": {
    "DataProcessRegion": {
     "CloudProvider": "AWS",
     "Region": "eu-west-1"
    },
    "ProjectId": "xxxxxxxxxxxxxxxxxxxx",
    "TenantName": "dev",
    "SkipRoleValidation": true,
    "Storage": {
     "Databases": [
...
     ],
     "Stores": [
      {
       "Name": "dev",
       "Provider": "atlas",
       "ClusterName": "dev",
       "ProjectId": "xxxxxxxxxxxxxxxxxxxx",
       "ReadPreference": {
        "Mode": "secondary",
        "TagSets": []
       }
      }
     ]
    },
    "Profile": "main"
   },
   "Metadata": {
    "aws:cdk:path": "dev-Backend/Db/FederatedDb"
   }
  },
```

Tried to give some values:

```
"DbFederatedDb5570C1CE": {
   "Type": "MongoDB::Atlas::FederatedDatabaseInstance",
   "Properties": {
    "CloudProviderConfig": {
     "ExternalId": "fed",
     "RoleId": "yyyyyyyyyyyyyyyyyyyyyy",
     "TestS3Bucket": "test-buck"
    },
    "DataProcessRegion": {
     "CloudProvider": "AWS",
     "Region": "eu-west-1"
    },
    "ProjectId": "xxxxxxxxxxxxxxxxxxxx",
    "TenantName": "dev",
    "SkipRoleValidation": true,
    "Storage": {
...
    },
    "Profile": "main"
   },
   "Metadata": {
    "aws:cdk:path": "dev-Backend/Db/FederatedDb"
   }
  },
```

**To Reproduce**

Create a CDK project with the following resource:

```
this.federatedInstance = new CfnFederatedDatabaseInstance(
			this,
			"FederatedDb",
			{
				projectId: this.projectId,
				tenantName: props.tenantName,
				profile: this.node.tryGetContext("mongoDBProfileName"),
				dataProcessRegion: {
					cloudProvider: "AWS",
					region: "eu-west-1",
				},
                      });
```

**Expected behavior**
Federated database created

**Screenshots**

**Please complete the following information:**
 - CFN resource version: Release date 2023-10-27 18:42:59 UTC+0200
 - AWS region where you are running the CFN stack: eu-west-3
 - CDK constructor type and version: 3.0.0
 - Copy of the output of `cdk synth`

**Comment by flochaz** [comment]
And indeed those, despite listed as optionals, seems required: https://github.com/mongodb/mongodbatlas-cloudformation-resources/blob/1cf90f1a3cf423a13de83f6e0cdc1c198acfb5c4/cfn-resources/federated-database-instance/mongodb-atlas-federateddatabaseinstance.json#L360

**Comment by Zuhairahmed** [comment]
Thanks @flochaz we are investing and will share feedback when we can.

**Comment by AgustinBettati** [comment]
Hello @flochaz, thank you for raising this issue.
I was able to reproduce your issue running a stack in CFN. This will likely require a change in our CFN implementation, an internal ticket has been created ([CLOUDP-219922](https://jira.mongodb.org/browse/CLOUDP-219922)) and we will let you know when we make progress on this.

**Comment by flochaz** [comment]
Great news thanks !

**Comment by oarbusi** [comment]
@flochaz In this [PR](https://github.com/mongodb/awscdk-resources-mongodbatlas/pull/264) we fix the issue you were facing. We will let you know once it's released. 
Keep in mind that there is no need to specify cloud provider because AWS is the default one.

**Comment by flochaz** [comment]
thx a lot
