### ISSUE TITLE
Better documentation around CfnCluster's `versionReleaseSystem` property

### ISSUE THREAD

**Issue by lockenj** [mongodb/awscdk-resources-mongodbatlas#175]
I am trying to understand how to configure my cluster to use the rapid release version any guidance would be helpful.

**Comment by Zuhairahmed** [comment]
hi @lockenj can you review `versionReleaseSystem` parameter here: https://constructs.dev/packages/awscdk-resources-mongodbatlas/v/3.0.1/api/CfnClusterProps?lang=typescript#property.versionReleaseSystem 

`versionReleaseSystem` is an optional parameter and represents the release cadence that Atlas uses for the cluster. This parameter defaults to `LTS`. If you set this field to `CONTINUOUS`, you must omit the `mongoDbMajorVersion` parameter. Atlas accepts:
- CONTINUOUS: Atlas creates your cluster using the most recent MongoDB release. Atlas automatically updates your cluster to the latest major and rapid MongoDB releases as they become available.

- LTS: Atlas creates your cluster using the latest patch release of the MongoDB version that you specify in the `mongoDbMajorVersion` field. Atlas automatically updates your cluster to subsequent patch releases of this MongoDB version. Atlas doesn't update your cluster to newer rapid or major MongoDB releases as they become available.

**Comment by lockenj** [comment]
@Zuhairahmed thanks for the speedy reply. I was trying to dig through the code to find the "enum". I am no stranger to having the docs miss some of the low level details. 

Is there somewhere in the source I could see possible values of properties?

I ask because I have encountered other properties in these CDK Constructs questions regarding available values.

For example: when trying to use the `CfnCustomDbRole` what are the possible actions? In the examples (`mongodb/awscdk-resources-mongodbatlas/examples/l1-resources/custom-db-role.ts`) I see action `GROUP_READ`, which I cannot find anywhere in the https://www.mongodb.com/docs/atlas/reference/custom-role-actions/ documentation.

Here is the example code from `custom-db-role.ts`: 
```
const customDbRole = new CfnCustomDbRole(this, 'CustomDbRole', {
      projectId: atlasProps.projId,
      profile: atlasProps.profile,
      actions:[
        {
          action: "GROUP_READ",
          resources: [
            {
              collection: atlasProps.collectionName,
            },
            {
              db: atlasProps.dbName,
            }
          ]
        }
      ],
      roleName: atlasProps.roleName,
    });
    ```
