### ISSUE TITLE
Need ability to lookup existing resources such as Project and Cluster

### ISSUE THREAD

**Issue by lockenj** [mongodb/awscdk-resources-mongodbatlas#178]
**Is your feature request related to a problem? Please describe.**
The AWS CDK allows you to access existing resources via static methods such as this one that allows you to lookup an existing VPC. https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_ec2.Vpc.html#static-fromwbrlookupscope-id-options

I need the ability to lookup existing projects, clusters etc to make modifications to them. 

**Describe the solution you'd like**
Here is the scenario... I have one stack that lays down the main infrastructure of the application including the mongo Atlas Cluster. I then have individual stacks that are my deployable services that add database users, roles etc... to the project and cluster. It would be nice to look these up instead of passing direct handles to the Project and Cluster constructs.

**Comment by Zuhairahmed** [comment]
Hi @lockenj, we have reached out to AWS CDK / CloudFormation team and then have informed us that full resource import (to access existing resources for example) is coming on their roadmap to third part resources like MongoDB Atlas, but is still several quarters away. We won't be able to support this feature request until AWS enables this for us. Feel free to reach out to us in case if you need anything else in the interim. Thank you

**Comment by lockenj** [comment]
Thanks @Zuhairahmed. Is there any github issue or something I can subscribe to so I know when this lands?
