### ISSUE TITLE
[Bug]: Create a MongoDB Atlas serverless cluster using CDK

### ISSUE THREAD

**Issue by ludoblues** [mongodb/awscdk-resources-mongodbatlas#185]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### CDK package version

v2.110.1

### CFN Resource version

v2.110.1

### CFN Resource Region

us-east-1

### Current Behavior

I am using SST and not directly CDK but this is not related, it looks like the interface of `AtlasServerlessBasic` i found here: https://constructs.dev/packages/awscdk-resources-mongodbatlas/v/3.1.0/api/AtlasServerlessBasicProps?lang=typescript may have some issues

I get the following error: `Template format error: Unrecognized resource types: [MongoDB::Atlas::Project, MongoDB::Atlas::DatabaseUser, MongoDB::Atlas::ProjectIpAccessList, MongoDB::Atlas::ServerlessInstance]`

### AWS CDK code to reproduce the issue

```typescript
new AtlasServerlessBasic(this, "Database", {
  projectProps: {
    orgId: "5aba***********",
  },
  serverlessProps: {}
});
```

### Steps To Reproduce

1. Instantiate a AtlasServerlessBasic Construct with all the required parameters

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by andreaangiolillo** [comment]
Hi @ludoblues 👋 Thanks for opening the issue.

Could you share the versions of the CFN resources that you activated in your AWS account in the region `us-east-1`? The error message seems to suggest that you did not activate them. You can use the construct [atlas-bootstrap](https://github.com/mongodb/awscdk-resources-mongodbatlas/tree/main/src/l3-resources/atlas-bootstrap) to speed up the process of activating the MongoDB Atlas CFN resources in your account.

**Comment by BwL1289** [comment]
This is still an issue. I cannot use MongoDB CDK constructs at all.

```
Error message
Template format error: Unrecognized resource types: [MongoDB::Atlas::NetworkPeering] (Service: AmazonCloudFormation; Status Code: 400; Error Code: ValidationError; Request ID: XXXXXX-XXXX-XXXX-XXXX-XXXXXXXXX; Proxy: null)
```
