### ISSUE TITLE
[Bug]: L1 resource name should not be randomized

### ISSUE THREAD

**Issue by pahud** [mongodb/awscdk-resources-mongodbatlas#209]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### CDK package version

latest

### CFN Resource version

n/a

### CFN Resource Region

n/a

### Current Behavior

Some L3 classes are creating L1 resources with random name suffix if undefined, which is an anti-pattern in CDK.

For example:

https://github.com/mongodb/awscdk-resources-mongodbatlas/blob/5c57dc83f747b11243f7f15e91c5d8748f3fc709/src/l3-resources/atlas-serverless-basic/index.ts#L95-L97

This means if I run `cdk diff` after a successful deployment without changing any props, `cdk diff` will indicate the resource would be replaced because the name would be changed.

<img width="1488" alt="image" src="https://github.com/mongodb/awscdk-resources-mongodbatlas/assets/278432/f75c9e63-5182-4fcc-99ec-c107b132653d">

This is very bad because the cluster or serverless instance would be destroyed with a new one created. You will lost all the data on it.

Generally, it's recommended to specify the name for L1 like

Option 1. 

```ts
name: props.name
```
(just leave it as undefined and cloudformation will generate a random name for you)

Option 2. 

```ts
name: props.name ?? `${id}-instance`
```

As the construct `id` would be static, you get a static unique ID like that.

### AWS CDK code to reproduce the issue

```typescript
n/a
```

### Steps To Reproduce

n /a

### cdk synth

```shell
n/a
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Zuhairahmed** [comment]
Thanks for flagging @pahud! this fix has been merged and published to NPM v3.1.1 update - https://www.npmjs.com/package/awscdk-resources-mongodbatlas
