### ISSUE TITLE
Not existing Users are not created by ressource "AtlasBasic"

### ISSUE THREAD

**Issue by romulus-ai** [mongodb/awscdk-resources-mongodbatlas#247]
**Is your feature request related to a problem? Please describe.**
When I create an AtlasBasic ressource, I could configure "clusterProps, projectProps, ipaccesslistProps", those are created if they not exist in my account. However if I define "dbUserProps", the user is not created, if it does not exist, I simply get an error that says "user cannot be found".

**Describe the solution you'd like**
I would expect to create the user if it does not exist, since if I create a project and cluster with this ressource, I will have an henn egg problem with the user, since the project must already exist to create the user. This means I have to use 3 Ressources to create a cluster, even if there is a ressource that should manage that.

**Describe alternatives you've considered**
Alternative is to not create the user, but it should be documented and explained, why.

**Additional context**

**Comment by lantoli** [comment]
thanks @romulus-ai for opening the issue.
can you please share the info requested including the CDK code and cdk synth output so we can know the code you're executing?

AtlasBasic L3 creates a DB user for you with default values:
const dbDefaults = {
  dbName: "admin",
  username: "atlas-user",
  password: "atlas-pwd",
  roles: [
    {
      roleName: "atlasAdmin",
      databaseName: "admin",
    },
  ],
};

but you can override those values, this is the code in the L3 that allows that:
    // Create a new MongoDB Atlas Database User
    this.mDBUser = new atlas.CfnDatabaseUser(this, "db-user-".concat(id), {
      profile: props.profile,
      databaseName: props.dbUserProps?.databaseName || dbDefaults.dbName,
      projectId: this.mProject.attrId,
      username: props.dbUserProps?.username || dbDefaults.username,
      roles: props.dbUserProps?.roles || dbDefaults.roles,
      password: props.dbUserProps?.password || dbDefaults.password,
      ...props.dbUserProps,
    });

thanks

**Comment by oarbusi** [comment]
Closing because inactivity
