### ISSUE TITLE
[Bug]: Fail to create CfnAuditing

### ISSUE THREAD

**Issue by flexelem** [mongodb/awscdk-resources-mongodbatlas#265]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### CDK package version

v3.3.0

### CFN Resource version

v2.81.0

### CFN Resource Region

us-east-1

### Current Behavior

We want to enable Auditing for our clusters by using `CfnAuditing` construct, however, we get `required key [ProjectId] not found #: extraneous key [GroupId] is not permitted` error from CloudFormation when deploying our stack.

### AWS CDK code to reproduce the issue

```typescript
new atlas_mongo.CfnAuditing(this, 'Auditing', {
      groupId: projectId,
});
```

### Steps To Reproduce

Create `CfnAuditing` construct with `groupId` set to `projectId`

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by lantoli** [comment]
thanks @flexelem for opening the issue.  

After some investigation I realized that the attribute was renamed in CFN from groupId for projectId but we didn't update CDK L1 construct. 

Sorry for the inconvenience, I'll create a PR to fix it and will publish a new CDK release with the fix.

**Comment by flexelem** [comment]
Thanks a lot @lantoli! I am looking forward for the release.

**Comment by lantoli** [comment]
@flexelem version 3.5.1 is already released with the fix.

Remember to change attribute name to projectId.

Closing the issue but feel free to reopen if you have any further question. thanks!
