### ISSUE TITLE
CfnCloudBackupSnapshotExportBucket requires iamRoleId, but it is unclear how to create this id / its creation does not seem to be supported in CDK.

### ISSUE THREAD

**Issue by rory-wilson** [mongodb/awscdk-resources-mongodbatlas#275]
**Is your feature request related to a problem? Please describe.**
Looking at the documentation for creating a snapshot extract bucket (https://github.com/mongodb/awscdk-resources-mongodbatlas/tree/ef4c0a5d15e15cac3a4f96d524aaf98e4a6966fa/src/l1-resources/cloud-backup-snapshot-export-bucket) this construct requires an `iamRoleId` of 24 characters. Using the Admin API, this can be created using the cloudProviderAccess endpoint (https://www.mongodb.com/docs/atlas/reference/api-resources-spec/v2/#tag/Cloud-Provider-Access/operation/createCloudProviderAccessRole) - this is then granted permission with a local IAM role with access to the bucket. 

This operation does not appear to exist with the CDK at present, and so creation of a snapshot export bucket is not possible. 

**Describe the solution you'd like**
Either update the documentation with a practical example showing how it is possible with the current CDK implementation, or add the cloudProviderAccess endpoint support into the CDK.

**Describe alternatives you've considered**
A mixed approach, using the CDK tools for project creation, and the API for cloud provider access, but with no success.

**Comment by marcosuma** [comment]
Thanks @rory-wilson for opening this issue with us. You are right, we don't have cloud-provider-access in CDK, but most importantly we don't have it in our CFN resources. Right now as you have already figured out, you can use the Atlas Admin API to create that or even better our Atlas CLI.

I know it's not an ideal experience, so I am going to bring this in for prioritization with the team and see what we can do.

FYI I'll track this with an internal issue, sorry I won't be able to show updates on that side.
Let me know how else I can help.

**Comment by marcosuma** [comment]
@rory-wilson in the meantime [this](https://feedback.mongodb.com/forums/924145-atlas?category_id=392596) is a good place where to leave this as a **feature request**
