### ISSUE TITLE
[Bug]: Version 3.5.2 is NOT backwards compatible with version 3.5.1 and below

### ISSUE THREAD

**Issue by lockenj** [mongodb/awscdk-resources-mongodbatlas#278]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### CDK package version

v3.5.2

### CFN Resource version

N/A

### CFN Resource Region

N/A

### Current Behavior

In version v3.5.1 the below snippet returns the standardSrv connection string.
```
this.#_atlasCluster.connectionStrings.standardSrv
```

Now in v3.5.2 I get error:
```
TypeError: Cannot read properties of undefined (reading 'standardSrv')
```

### AWS CDK code to reproduce the issue

```typescript
this.#_atlasCluster.connectionStrings.standardSrv
```

### Steps To Reproduce

This will fail using cdk Synth

### cdk synth

```shell
TypeError: Cannot read properties of undefined (reading 'standardSrv')
      at new MongoAtlasConstruct (file:///home/runner/work/frank/frank/packages/infra-libs/core-environment/lib/MongoAtlasConstruct.mjs:235:107)
      at new TestStack (file:///home/runner/work/frank/frank/packages/infra-libs/core-environment/test/unit/mongo.test.mjs:15:44)
      at Context.<anonymous> (file:///home/runner/work/frank/frank/packages/infra-libs/core-environment/test/unit/mongo.test.mjs:24:23)
      at process.processImmediate (node:internal/timers:478:21)
```
```


### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by lockenj** [comment]
See [PR 277](https://github.com/mongodb/awscdk-resources-mongodbatlas/pull/277)

**Comment by lantoli** [comment]
sorry @lockenj for the inconvenience.

that property shouldn't have existed in the first place. It was manually added so it was not synced with underlaying CFN resource. This CDK L1 resource must be generated automatically.

If you need to access those properties, you can do things like:

this.#_atlasCluster.getAtt("ConnectionStrings.StandardSrv")
you can take this PR code change as a reference.

thanks

**Comment by lantoli** [comment]
@lockenj @romulus-ai thanks for your understanding, I'm happy that the proposed solution works for you as in the PR comments https://github.com/mongodb/awscdk-resources-mongodbatlas/pull/277. 

closing this issue but don't hesitate to ask any other question you have.
