### ISSUE TITLE
Problem obtaining Connection String property

### ISSUE THREAD

**Issue by TadeoCloud** [mongodb/awscdk-resources-mongodbatlas#369]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### CDK package version

v3.9.0

### CFN Resource version

cluster:v2.3.0

### CFN Resource Region

eu-west-1

### Current Behavior

I unable to obtain the Connection String from the CfnCluster (MongoDB::Atlas::Cluster) L1 property.

I want to get the standard and/o privateLink Connection String from Atlas cluster. In previus version (1.0.2) of this lib I can get at least StandardSrv ConnectionString using L3 construct: this.cluster.atlasBasic.mCluster.connectionStrings.standardSrv

Now using CfnCluster L1 resource in v3.9.0 lib I unable to obtain a Connection String. It doesn't matter if I try to get cluster.props.connectionStrings?.standardSrv, standard, privateSrv, privateEndpointsSrv[0]... All are empty

### AWS CDK code to reproduce the issue

```typescript
import { Construct } from 'constructs';
import { CfnCluster} from 'awscdk-resources-mongodbatlas';

export class MongoCluster extends Construct {
  constructor(scope: Construct, id: string, props: MongoClusterProps) {
    super(scope, id);

    const cluster = new CfnCluster(this, "cluster", {
      projectId: "xxxxxxxxxxx",
      name: "cluster_name",
    });

    new CfnOutput(this, 'standard', {
      value: cluster.props.connectionStrings?.standardSrv ?? 'undefined',
    });

    new CfnOutput(this, 'privateSrv', {
      value: cluster.props.connectionStrings?.privateSrv ?? 'undefined',
      exportName: 'cluster-props-connectionStrings-privateSrv'
    });
  }
}
```

### Steps To Reproduce

1. Create new CfnCluster
2. Try to obtain Connection String from CfnCluster props

### cdk synth

```shell
MongoAtlasMongoprivateF5D73872:
    Value: undefined
  MongoAtlasMongoprivateSrv44B21F6A:
    Value: undefined
  MongoAtlasMongostandardDC6D2AB3:
    Value: undefined
  MongoAtlasMongostandardSrvEFF11DC7:
    Value: undefined
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by marcosuma** [comment]
From a quick check I did using atlas cli, when I create the cluster the connection strings are not immediately returned, it should be only after the cluster hardware is fully ready.. here's my example:

```
atlas clusters create testcluster02022024 --provider=AWS --region=US_EAST_2 --projectId ...

{
  "backupEnabled": true,
  "biConnector": {
    "enabled": false,
    "readPreference": "secondary"
  },
  "clusterType": "REPLICASET",
  "connectionStrings": {},
  "createDate": "2024-10-16T09:09:21Z",
  "diskSizeGB": 2,
  "diskWarmingMode": "FULLY_WARMED",
  "encryptionAtRestProvider": "NONE",
  "globalClusterSelfManagedSharding": false,
  "groupId": "...",
  "id": "...",
  "labels": [],
  "links": [
    {
      "href": "...",
      "rel": "self"
    },
    {
      "href": "...",
      "rel": "https://cloud.mongodb.com/restoreJobs"
    },
    {
      "href": "...",
      "rel": "https://cloud.mongodb.com/snapshots"
    }
  ],
  "mongoDBMajorVersion": "7.0",
  "mongoDBVersion": "7.0.14",
  "name": "...",
  "paused": false,
  "pitEnabled": false,
  "replicationSpecs": [
    {
      "id": "...",
      "numShards": 1,
      "regionConfigs": [
        {
          "electableSpecs": {
            "instanceSize": "M2"
          },
          "priority": 7,
          "providerName": "TENANT",
          "regionName": "US_EAST_2",
          "backingProviderName": "AWS"
        }
      ],
      "zoneName": "Zone 1"
    }
  ],
  "rootCertType": "ISRGROOTX1",
  "stateName": "CREATING",
  "terminationProtectionEnabled": false,
  "versionReleaseSystem": "LTS"
}

```

**Comment by TadeoCloud** [comment]
Thank for your reply @marcosuma 

I've been investigating in depth and realized that in the 1.0.2 version of library the ConnectionString was obtained in this way:

    const connStringsStandardSrv = cdk.Token.asString(
      this.getAtt(“ConnectionStrings.StandardSrv”)
    );

Using last lib version (3.9.x) the previous code has disappeared BUT I can still obtain this attribute from my "cluster" object in my example.

    const connStringsStandardSrv = cdk.Token.asString(
      cluster.getAtt("ConnectionStrings.StandardSrv")
    );


Seems the problem is solved

**Comment by marcosuma** [comment]
Great! Glad you managed to figure that out, closing this issue for now - feel free to come back if you need more help :)
