### ISSUE TITLE
Interoperatibility of cdk stack with mongodb web ui

### ISSUE THREAD

**Issue by dahiyahimanshu** [mongodb/awscdk-resources-mongodbatlas#39]
Hi,

As we are creating mongodb atlas stack from cdk. the same is not reflecting in mongo db ui once created. in my view. there should be interoperability between these 2 systems.

**Comment by Zuhairahmed** [comment]
hi @dahiyahimanshu can you share more details on you question? would be helpful to have:

CFN resource version
AWS region where you are running the CFN stack
CDK constructor type and version
Copy of the output of cdk synth
also full list of AWS CDK constructs are here: https://constructs.dev/packages/awscdk-resources-mongodbatlas/v/1.0.1?lang=typescript

if you are seeking to put in a feature request for a new resource you can do so at: https://feedback.mongodb.com/forums/924145-atlas?category_id=392596

**Comment by dahiyahimanshu** [comment]
working for me with org admin permission. thanks
