### ISSUE TITLE
How to expose CDC to kafka through CDK?

### ISSUE THREAD

**Issue by dahiyahimanshu** [mongodb/awscdk-resources-mongodbatlas#48]
As we are required to plug Mongodb CDC to kafka. How to configure that through CDK please? We are using AtlasBasicPrivateEndpoint constrcut

**Comment by Zuhairahmed** [comment]
hi @dahiyahimanshu can you share more details on you question? would be helpful to have: 
 - CFN resource version 
 - AWS region where you are running the CFN stack
 - CDK constructor type and version
 - Copy of the output of `cdk synth`

also full list of AWS CDK constructs are here: https://constructs.dev/packages/awscdk-resources-mongodbatlas/v/1.0.1?lang=typescript 

if you are seeking to put in a feature request for a new resource you can do so at: https://feedback.mongodb.com/forums/924145-atlas?category_id=392596

**Comment by dahiyahimanshu** [comment]
is there any readymade example which uses https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_kafkaconnect.CfnConnector.html

i am following up on this https://www.mongodb.com/developer/languages/java/integrating-mongodb-amazon-apache-kafka/ but want to get it done through cdk

**Comment by Zuhairahmed** [comment]
hi @dahiyahimanshu not yet, but feel free to make a suggestion for this example on our [product feedback portal](https://feedback.mongodb.com/forums/924145-atlas?category_id=392596). this will help us prioritize creating this one over other items on our roadmap. hope this helps!
