### ISSUE TITLE
Extend AtlasBasic DatabaseUserProps to support 'SecretValue'

### ISSUE THREAD

**Issue by coldfire84** [mongodb/awscdk-resources-mongodbatlas#59]
I may be missing something (obvious), and apologies if I am... I am using AWS Secrets Manager in my CDK stack, generating a new secret as outlined [here](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_secretsmanager-readme.html).

I am running into an issue where the AtlasBasic 'dbUserProps' interface will only accept a string, not a SecretValue (error shown is ```Type 'SecretValue' is not assignable to type 'string'```):

```
...
// Create new Secret
const templatedSecret = new sm.Secret(this, "AtlasDbUser", {
  generateSecretString: {
    secretStringTemplate: JSON.stringify({
      username: `myUser`,
    }),
    generateStringKey: "password",
  },
});

// Create Atlas Project/ Cluster
const atlasDb = new AtlasBasic(this, "AtlasBasic", {
      dbUserProps: {
        username: templatedSecret.secretValueFromJson("username"), // <-- this causes an error as it is a SecretValue, not string
        password: templatedSecret.secretValueFromJson("password"), // <-- as above
        databaseName: context.atlasAuthenticationDatabaseName,
        roles: [
          {
            roleName: "dbOwner",
            databaseName: context.atlasDatabaseName,
          },
        ],
      },
 ...
```

I would like to to avoid the need to use '[unsafeUnwrap()](https://docs.aws.amazon.com/cdk/api/v1/docs/@aws-cdk_core.SecretValue.html#unsafewbrunwrap)' on the secret and just use the SecretValue. Using the `toString()` as outlined in the first link, also yields an error, pointing in the direction of 'secretValue.unsafeUnwrap()' but carries the warning "if you understand and accept the risks.."

In terms of alternatives. I want to avoid using 'unsafeUnwrap()' on the secret value for a variety of reasons outlined in the AWS docs. If there is another approach, that will ensure the secret does not end up in the IaC/ CI logs etc., then I'm happy to look at alternatives.

**Comment by Adelmar92** [comment]
hello @coldfire84 so there is an option to use this:
![image](https://github.com/mongodb/awscdk-resources-mongodbatlas/assets/69170650/d2f6aef5-f4c0-404c-9b42-c6eaa79bab47)

**Comment by jonslo** [comment]
> hello @coldfire84 so there is an option to use this: ![image](https://private-user-images.githubusercontent.com/69170650/255714120-d2f6aef5-f4c0-404c-9b42-c6eaa79bab47.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ0MDczMDQsIm5iZiI6MTcwNDQwNzAwNCwicGF0aCI6Ii82OTE3MDY1MC8yNTU3MTQxMjAtZDJmNmFlZjUtZjRjMC00MDRjLTliNDItYzZlYWE3OWJhYjQ3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA0VDIyMjMyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNlZjVlYmY3MGFmN2I5Zjc2NjRmN2ZjYmRjMzcxOGUxZTAzMGQ4YjBlZDFjYjk1MmUxMzJjNTQzY2NiYzM2MjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ayj38c6zCCOkSxjFfz0YHOGNEPUdwXpCdFKTsKZ4N5s)

As @coldfire84 had mentioned, using the `unsafeUnwrap()` call makes the secrets visible in the output template, logs, etc. It defeats the point of using Secrets Manager. Making the username/password values in CfnDatabaseUser use SecretValue types would keep the credentials secure.
