### ISSUE TITLE
Creation of database trigger with match expression fails

### ISSUE THREAD

**Issue by StefanWachter1507** [mongodb/awscdk-resources-mongodbatlas#80]
Note: I also filed this issue under [mongodbatlas-cloudformation-resources/issues/592](https://github.com/mongodb/mongodbatlas-cloudformation-resources/issues/592) because I do not know if this is a CDK related problem or related to the underlying CloudFormation resources.

I try to use the `CfnTrigger` construct to create a database trigger:

```
new CfnTrigger(this, 'trigger', {
            name,
            projectId,
            appId,
            type: 'DATABASE',
            databaseTrigger: {
                serviceId,
                database,
                collection,
                operationTypes: [DatabaseConfigOperationTypes.UPDATE],
                match: {
                    $expr: {
                        $and: [
                            {
                                $eq: ['$fullDocument.availability.value', 'AVAILABLE']
                            },
                            {
                                $ne: ['$fullDocument.retailPrice', '$fullDocumentBeforeChange.retailPrice']
                            }
                        ]
                    }
                },
            },
            eventProcessors: {
                awseventbridge: {
                    awsConfig: {
                        region,
                        accountId
                    }
                }
            }
        });
```

Deploying this construct results in the following failure.

```
9:14:31 AM | CREATE_FAILED        | MongoDB::Atlas::Trigger | triggerCD2FF5BD
Resource handler returned message: "Unable to complete request: Marshaling: Unable to convert type
caused by: Unsupported type interface {}" (RequestToken: 993412b5-8ea7-4a60-c3f6-e7983d7e9c57, HandlerErrorCode: GeneralServiceException)
```

When the `match` property is removed then the trigger is deployed successfully.

**Comment by Zuhairahmed** [comment]
@StefanWachter1507 and @Adelmar92 can you confirm if this issue has been resolved?

**Comment by Adelmar92** [comment]
hello @StefanWachter1507 the match expression should be a Stringify version of the expression, can you follow this https://github.com/mongodb/mongodbatlas-cloudformation-resources/blob/c9c94752b2b36249af1297438555f7e980a39f3a/examples/trigger/trigger.json#L53 con confirm me if it works??

**Comment by Zuhairahmed** [comment]
thanks again, let us know if you need anything else here. resolving issue
